/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package abgabe3;

import data.Student;
import menu.Factory;
import stack.Stack;

public class App {

    public static void main(String[] args) {
        Stack<Student> stack = new Stack<>();
        Factory.menu(stack);

    }
}
